/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateNewTeamRequestPlayerDetails } from './createNewTeamRequestPlayerDetails';


export interface CreateNewTeamRequest { 
    /**
     * The dedicated for the server team
     */
    serverName: string;
    /**
     * The League of Legends Clash Tournament to sign up for
     */
    tournamentName: string;
    /**
     * The Tournament day to sign up for
     */
    tournamentDay: string;
    playerDetails: CreateNewTeamRequestPlayerDetails;
}

