/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { Subscription } from './subscription';


/**
 * A Clash Bot Player
 */
export interface Player { 
    /**
     * Unique identifier for Player
     */
    id?: string;
    /**
     * The Players discord name
     */
    name?: string;
    role?: Role;
    /**
     * A list of the Users preferred champions.
     */
    champions?: Array<string>;
    subscriptions?: Array<Subscription>;
    serverName?: string;
}

