/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A League of Legends role.
 */
export type Role = 'Top' | 'Mid' | 'Jg' | 'Bot' | 'Supp';

export const Role = {
    Top: 'Top' as Role,
    Mid: 'Mid' as Role,
    Jg: 'Jg' as Role,
    Bot: 'Bot' as Role,
    Supp: 'Supp' as Role
};

