/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ClashBotRestClient&#x3D;projectVersion&#x3D;100);
  }
}(this, function(expect, ClashBotRestClient&#x3D;projectVersion&#x3D;100) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ClashBotRestClient&#x3D;projectVersion&#x3D;100.UserApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserApi', function() {
    describe('addToListOfPreferredChampions', function() {
      it('should call addToListOfPreferredChampions successfully', function(done) {
        //uncomment below and update the code to test addToListOfPreferredChampions
        //instance.addToListOfPreferredChampions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createNewListOfPreferredChampions', function() {
      it('should call createNewListOfPreferredChampions successfully', function(done) {
        //uncomment below and update the code to test createNewListOfPreferredChampions
        //instance.createNewListOfPreferredChampions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createUser', function() {
      it('should call createUser successfully', function(done) {
        //uncomment below and update the code to test createUser
        //instance.createUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUser', function() {
      it('should call getUser successfully', function(done) {
        //uncomment below and update the code to test getUser
        //instance.getUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeFromListOfPreferredChampions', function() {
      it('should call removeFromListOfPreferredChampions successfully', function(done) {
        //uncomment below and update the code to test removeFromListOfPreferredChampions
        //instance.removeFromListOfPreferredChampions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveListOfUserPreferredChampions', function() {
      it('should call retrieveListOfUserPreferredChampions successfully', function(done) {
        //uncomment below and update the code to test retrieveListOfUserPreferredChampions
        //instance.retrieveListOfUserPreferredChampions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveUserSubscriptions', function() {
      it('should call retrieveUserSubscriptions successfully', function(done) {
        //uncomment below and update the code to test retrieveUserSubscriptions
        //instance.retrieveUserSubscriptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subscribeUser', function() {
      it('should call subscribeUser successfully', function(done) {
        //uncomment below and update the code to test subscribeUser
        //instance.subscribeUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('unsubscribeUser', function() {
      it('should call unsubscribeUser successfully', function(done) {
        //uncomment below and update the code to test unsubscribeUser
        //instance.unsubscribeUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUser', function() {
      it('should call updateUser successfully', function(done) {
        //uncomment below and update the code to test updateUser
        //instance.updateUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
