/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddToListOfPreferredChampionsRequest model module.
 * @module model/AddToListOfPreferredChampionsRequest
 * @version 1.0.0
 */
class AddToListOfPreferredChampionsRequest {
    /**
     * Constructs a new <code>AddToListOfPreferredChampionsRequest</code>.
     * @alias module:model/AddToListOfPreferredChampionsRequest
     * @param championName {String} 
     */
    constructor(championName) { 
        
        AddToListOfPreferredChampionsRequest.initialize(this, championName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, championName) { 
        obj['championName'] = championName;
    }

    /**
     * Constructs a <code>AddToListOfPreferredChampionsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddToListOfPreferredChampionsRequest} obj Optional instance to populate.
     * @return {module:model/AddToListOfPreferredChampionsRequest} The populated <code>AddToListOfPreferredChampionsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddToListOfPreferredChampionsRequest();

            if (data.hasOwnProperty('championName')) {
                obj['championName'] = ApiClient.convertToType(data['championName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} championName
 */
AddToListOfPreferredChampionsRequest.prototype['championName'] = undefined;






export default AddToListOfPreferredChampionsRequest;

