/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateNewListOfPreferredChampionsRequest model module.
 * @module model/CreateNewListOfPreferredChampionsRequest
 * @version 1.0.0
 */
class CreateNewListOfPreferredChampionsRequest {
    /**
     * Constructs a new <code>CreateNewListOfPreferredChampionsRequest</code>.
     * @alias module:model/CreateNewListOfPreferredChampionsRequest
     * @param champions {Array.<String>} 
     */
    constructor(champions) { 
        
        CreateNewListOfPreferredChampionsRequest.initialize(this, champions);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, champions) { 
        obj['champions'] = champions;
    }

    /**
     * Constructs a <code>CreateNewListOfPreferredChampionsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateNewListOfPreferredChampionsRequest} obj Optional instance to populate.
     * @return {module:model/CreateNewListOfPreferredChampionsRequest} The populated <code>CreateNewListOfPreferredChampionsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateNewListOfPreferredChampionsRequest();

            if (data.hasOwnProperty('champions')) {
                obj['champions'] = ApiClient.convertToType(data['champions'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} champions
 */
CreateNewListOfPreferredChampionsRequest.prototype['champions'] = undefined;






export default CreateNewListOfPreferredChampionsRequest;

