/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Role from './Role';

/**
 * The CreateNewTeamRequestPlayerDetails model module.
 * @module model/CreateNewTeamRequestPlayerDetails
 * @version 1.0.0
 */
class CreateNewTeamRequestPlayerDetails {
    /**
     * Constructs a new <code>CreateNewTeamRequestPlayerDetails</code>.
     * @alias module:model/CreateNewTeamRequestPlayerDetails
     */
    constructor() { 
        
        CreateNewTeamRequestPlayerDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateNewTeamRequestPlayerDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateNewTeamRequestPlayerDetails} obj Optional instance to populate.
     * @return {module:model/CreateNewTeamRequestPlayerDetails} The populated <code>CreateNewTeamRequestPlayerDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateNewTeamRequestPlayerDetails();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = Role.constructFromObject(data['role']);
            }
        }
        return obj;
    }


}

/**
 * Unique identifier for Player
 * @member {String} id
 */
CreateNewTeamRequestPlayerDetails.prototype['id'] = undefined;

/**
 * @member {module:model/Role} role
 */
CreateNewTeamRequestPlayerDetails.prototype['role'] = undefined;






export default CreateNewTeamRequestPlayerDetails;

