/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetApplicationHealth200Response model module.
 * @module model/GetApplicationHealth200Response
 * @version 1.0.0
 */
class GetApplicationHealth200Response {
    /**
     * Constructs a new <code>GetApplicationHealth200Response</code>.
     * @alias module:model/GetApplicationHealth200Response
     */
    constructor() { 
        
        GetApplicationHealth200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetApplicationHealth200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetApplicationHealth200Response} obj Optional instance to populate.
     * @return {module:model/GetApplicationHealth200Response} The populated <code>GetApplicationHealth200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetApplicationHealth200Response();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Is the instance healthy
 * @member {String} status
 */
GetApplicationHealth200Response.prototype['status'] = undefined;






export default GetApplicationHealth200Response;

