/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Role.
* @enum {}
* @readonly
*/
export default class Role {
    
        /**
         * value: "Top"
         * @const
         */
        "Top" = "Top";

    
        /**
         * value: "Mid"
         * @const
         */
        "Mid" = "Mid";

    
        /**
         * value: "Jg"
         * @const
         */
        "Jg" = "Jg";

    
        /**
         * value: "Bot"
         * @const
         */
        "Bot" = "Bot";

    
        /**
         * value: "Supp"
         * @const
         */
        "Supp" = "Supp";

    

    /**
    * Returns a <code>Role</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Role} The enum <code>Role</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

