/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Player from './Player';

/**
 * The TeamPlayerDetails model module.
 * @module model/TeamPlayerDetails
 * @version 1.0.0
 */
class TeamPlayerDetails {
    /**
     * Constructs a new <code>TeamPlayerDetails</code>.
     * @alias module:model/TeamPlayerDetails
     */
    constructor() { 
        
        TeamPlayerDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamPlayerDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TeamPlayerDetails} obj Optional instance to populate.
     * @return {module:model/TeamPlayerDetails} The populated <code>TeamPlayerDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamPlayerDetails();

            if (data.hasOwnProperty('Top')) {
                obj['Top'] = Player.constructFromObject(data['Top']);
            }
            if (data.hasOwnProperty('Mid')) {
                obj['Mid'] = Player.constructFromObject(data['Mid']);
            }
            if (data.hasOwnProperty('Jg')) {
                obj['Jg'] = Player.constructFromObject(data['Jg']);
            }
            if (data.hasOwnProperty('Bot')) {
                obj['Bot'] = Player.constructFromObject(data['Bot']);
            }
            if (data.hasOwnProperty('Supp')) {
                obj['Supp'] = Player.constructFromObject(data['Supp']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Player} Top
 */
TeamPlayerDetails.prototype['Top'] = undefined;

/**
 * @member {module:model/Player} Mid
 */
TeamPlayerDetails.prototype['Mid'] = undefined;

/**
 * @member {module:model/Player} Jg
 */
TeamPlayerDetails.prototype['Jg'] = undefined;

/**
 * @member {module:model/Player} Bot
 */
TeamPlayerDetails.prototype['Bot'] = undefined;

/**
 * @member {module:model/Player} Supp
 */
TeamPlayerDetails.prototype['Supp'] = undefined;






export default TeamPlayerDetails;

