/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TeamPlayerDetails from './TeamPlayerDetails';
import Tournament from './Tournament';

/**
 * The Team model module.
 * @module model/Team
 * @version 1.0.0
 */
class Team {
    /**
     * Constructs a new <code>Team</code>.
     * A League of Legends Clash Team
     * @alias module:model/Team
     */
    constructor() { 
        
        Team.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Team</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Team} obj Optional instance to populate.
     * @return {module:model/Team} The populated <code>Team</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Team();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('playerDetails')) {
                obj['playerDetails'] = TeamPlayerDetails.constructFromObject(data['playerDetails']);
            }
            if (data.hasOwnProperty('serverName')) {
                obj['serverName'] = ApiClient.convertToType(data['serverName'], 'String');
            }
            if (data.hasOwnProperty('tournament')) {
                obj['tournament'] = Tournament.constructFromObject(data['tournament']);
            }
        }
        return obj;
    }


}

/**
 * The name of the Team.
 * @member {String} name
 */
Team.prototype['name'] = undefined;

/**
 * @member {module:model/TeamPlayerDetails} playerDetails
 */
Team.prototype['playerDetails'] = undefined;

/**
 * The Discord server that the Team belongs to.
 * @member {String} serverName
 */
Team.prototype['serverName'] = undefined;

/**
 * @member {module:model/Tournament} tournament
 */
Team.prototype['tournament'] = undefined;






export default Team;

