/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Player from './Player';
import Tournament from './Tournament';

/**
 * The Tentative model module.
 * @module model/Tentative
 * @version 1.0.0
 */
class Tentative {
    /**
     * Constructs a new <code>Tentative</code>.
     * A queue for Players unsure if they will play Clash for a given Tournament.
     * @alias module:model/Tentative
     */
    constructor() { 
        
        Tentative.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Tentative</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tentative} obj Optional instance to populate.
     * @return {module:model/Tentative} The populated <code>Tentative</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tentative();

            if (data.hasOwnProperty('serverName')) {
                obj['serverName'] = ApiClient.convertToType(data['serverName'], 'String');
            }
            if (data.hasOwnProperty('tournamentDetails')) {
                obj['tournamentDetails'] = Tournament.constructFromObject(data['tournamentDetails']);
            }
            if (data.hasOwnProperty('tentativePlayers')) {
                obj['tentativePlayers'] = ApiClient.convertToType(data['tentativePlayers'], [Player]);
            }
        }
        return obj;
    }


}

/**
 * The Server that the tentative queue belongs to.
 * @member {String} serverName
 */
Tentative.prototype['serverName'] = undefined;

/**
 * @member {module:model/Tournament} tournamentDetails
 */
Tentative.prototype['tournamentDetails'] = undefined;

/**
 * @member {Array.<module:model/Player>} tentativePlayers
 */
Tentative.prototype['tentativePlayers'] = undefined;






export default Tentative;

