/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Tournament model module.
 * @module model/Tournament
 * @version 1.0.0
 */
class Tournament {
    /**
     * Constructs a new <code>Tournament</code>.
     * A League of Legends Clash Tournament
     * @alias module:model/Tournament
     */
    constructor() { 
        
        Tournament.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Tournament</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tournament} obj Optional instance to populate.
     * @return {module:model/Tournament} The populated <code>Tournament</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tournament();

            if (data.hasOwnProperty('tournamentName')) {
                obj['tournamentName'] = ApiClient.convertToType(data['tournamentName'], 'String');
            }
            if (data.hasOwnProperty('tournamentDay')) {
                obj['tournamentDay'] = ApiClient.convertToType(data['tournamentDay'], 'String');
            }
            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'Date');
            }
            if (data.hasOwnProperty('registrationTime')) {
                obj['registrationTime'] = ApiClient.convertToType(data['registrationTime'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * The name of the Tournament.
 * @member {String} tournamentName
 */
Tournament.prototype['tournamentName'] = undefined;

/**
 * The day number of the Tournament. [1-4]
 * @member {String} tournamentDay
 */
Tournament.prototype['tournamentDay'] = undefined;

/**
 * When the Tournament starts.
 * @member {Date} startTime
 */
Tournament.prototype['startTime'] = undefined;

/**
 * When you can register for the Tournament.
 * @member {Date} registrationTime
 */
Tournament.prototype['registrationTime'] = undefined;






export default Tournament;

