/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Role from './Role';
import Tournament from './Tournament';

/**
 * The UpdateTeamRequest model module.
 * @module model/UpdateTeamRequest
 * @version 1.0.0
 */
class UpdateTeamRequest {
    /**
     * Constructs a new <code>UpdateTeamRequest</code>.
     * @alias module:model/UpdateTeamRequest
     * @param serverName {String} 
     * @param teamName {String} 
     * @param tournamentDetails {module:model/Tournament} 
     * @param playerId {String} Player id to add to Team.
     * @param role {module:model/Role} 
     */
    constructor(serverName, teamName, tournamentDetails, playerId, role) { 
        
        UpdateTeamRequest.initialize(this, serverName, teamName, tournamentDetails, playerId, role);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, serverName, teamName, tournamentDetails, playerId, role) { 
        obj['serverName'] = serverName;
        obj['teamName'] = teamName;
        obj['tournamentDetails'] = tournamentDetails;
        obj['playerId'] = playerId;
        obj['role'] = role;
    }

    /**
     * Constructs a <code>UpdateTeamRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateTeamRequest} obj Optional instance to populate.
     * @return {module:model/UpdateTeamRequest} The populated <code>UpdateTeamRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateTeamRequest();

            if (data.hasOwnProperty('serverName')) {
                obj['serverName'] = ApiClient.convertToType(data['serverName'], 'String');
            }
            if (data.hasOwnProperty('teamName')) {
                obj['teamName'] = ApiClient.convertToType(data['teamName'], 'String');
            }
            if (data.hasOwnProperty('tournamentDetails')) {
                obj['tournamentDetails'] = Tournament.constructFromObject(data['tournamentDetails']);
            }
            if (data.hasOwnProperty('playerId')) {
                obj['playerId'] = ApiClient.convertToType(data['playerId'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = Role.constructFromObject(data['role']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} serverName
 */
UpdateTeamRequest.prototype['serverName'] = undefined;

/**
 * @member {String} teamName
 */
UpdateTeamRequest.prototype['teamName'] = undefined;

/**
 * @member {module:model/Tournament} tournamentDetails
 */
UpdateTeamRequest.prototype['tournamentDetails'] = undefined;

/**
 * Player id to add to Team.
 * @member {String} playerId
 */
UpdateTeamRequest.prototype['playerId'] = undefined;

/**
 * @member {module:model/Role} role
 */
UpdateTeamRequest.prototype['role'] = undefined;






export default UpdateTeamRequest;

