/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamPlayerDetails } from './teamPlayerDetails';
import { Team } from './team';
import { Tournament } from './tournament';
import { RemovePlayerFromTeam200ResponseOneOf } from './removePlayerFromTeam200ResponseOneOf';


/**
 * @type RemovePlayerFromTeam200Response
 * @export
 */
export type RemovePlayerFromTeam200Response = RemovePlayerFromTeam200ResponseOneOf | Team;

