/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamPlayerDetails } from './teamPlayerDetails';
import { Tournament } from './tournament';


/**
 * A League of Legends Clash Team
 */
export interface Team { 
    /**
     * The name of the Team.
     */
    name?: string;
    playerDetails?: TeamPlayerDetails;
    /**
     * The Discord server that the Team belongs to.
     */
    serverName?: string;
    tournament?: Tournament;
}

