/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Player } from './player';
import { Tournament } from './tournament';


/**
 * A queue for Players unsure if they will play Clash for a given Tournament.
 */
export interface Tentative { 
    /**
     * The Server that the tentative queue belongs to.
     */
    serverName?: string;
    tournamentDetails?: Tournament;
    tentativePlayers?: Array<Player>;
}

