/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A League of Legends Clash Tournament
 */
export interface Tournament { 
    /**
     * The name of the Tournament.
     */
    tournamentName?: string;
    /**
     * The day number of the Tournament. [1-4]
     */
    tournamentDay?: string;
    /**
     * When the Tournament starts.
     */
    startTime?: string;
    /**
     * When you can register for the Tournament.
     */
    registrationTime?: string;
}

