/**
 * clash-bot-webapp-service
 * Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ClashBotRestClient&#x3D;projectVersion&#x3D;100);
  }
}(this, function(expect, ClashBotRestClient&#x3D;projectVersion&#x3D;100) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ClashBotRestClient&#x3D;projectVersion&#x3D;100.TeamPlayerDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TeamPlayerDetails', function() {
    it('should create an instance of TeamPlayerDetails', function() {
      // uncomment below and update the code to test TeamPlayerDetails
      //var instance = new ClashBotRestClient&#x3D;projectVersion&#x3D;100.TeamPlayerDetails();
      //expect(instance).to.be.a(ClashBotRestClient&#x3D;projectVersion&#x3D;100.TeamPlayerDetails);
    });

    it('should have the property top (base name: "Top")', function() {
      // uncomment below and update the code to test the property top
      //var instance = new ClashBotRestClient&#x3D;projectVersion&#x3D;100.TeamPlayerDetails();
      //expect(instance).to.be();
    });

    it('should have the property mid (base name: "Mid")', function() {
      // uncomment below and update the code to test the property mid
      //var instance = new ClashBotRestClient&#x3D;projectVersion&#x3D;100.TeamPlayerDetails();
      //expect(instance).to.be();
    });

    it('should have the property jg (base name: "Jg")', function() {
      // uncomment below and update the code to test the property jg
      //var instance = new ClashBotRestClient&#x3D;projectVersion&#x3D;100.TeamPlayerDetails();
      //expect(instance).to.be();
    });

    it('should have the property bot (base name: "Bot")', function() {
      // uncomment below and update the code to test the property bot
      //var instance = new ClashBotRestClient&#x3D;projectVersion&#x3D;100.TeamPlayerDetails();
      //expect(instance).to.be();
    });

    it('should have the property supp (base name: "Supp")', function() {
      // uncomment below and update the code to test the property supp
      //var instance = new ClashBotRestClient&#x3D;projectVersion&#x3D;100.TeamPlayerDetails();
      //expect(instance).to.be();
    });

  });

}));
